# Generated by Django 5.2.5 on 2025-08-24 21:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('sender_id', models.CharField(max_length=11)),
                ('recipient', models.CharField(max_length=15)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('encoding', models.CharField(choices=[('GSM-7', 'GSM-7'), ('UCS-2', 'UCS-2')], default='GSM-7', max_length=5)),
                ('segment_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
