# Generated by Django 5.2.5 on 2025-08-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
